--- #YAML:1.0
name:                Catalyst-Plugin-Session-Store-Cache
version:             0.01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst::Plugin::Session:     0.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
